### ISSUE TITLE
NotSslRecordException: not an SSL/TLS recod

### ISSUE THREAD

**Issue by mstya** [sscarduzio/elasticsearch-readonlyrest-plugin#126]
Hello!

Firstly, I want to apologize for my English:)
and I want to apologize for possible simple questions

I have a trouble with installing readonlyrest-plugin.
I have followed the steps from installation description and stuck on
```
ssl:
      enable: true
      keystore_file: "/elasticsearch/plugins/readonlyrest/keystore.jks"
      keystore_pass: readonlyrest
      key_pass: readonlyrest
```
I don't know how to generate keystore.jks correctly
In Internet I found that this file is generated by keytool program and I got it.
After next steps I started elasticsearch I went to the localhost:9200 and got this exception:

```
[2016-11-04 12:24:12,023][WARN ][plugin.readonlyrest      ] [Ezekiel Sims] Caught exception while handling client http traffic, closing connection [id: 0xea6ff12f, /10.10.40.14:53029 => /10.10.40.14:9200]
org.jboss.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 474554202f20485454502f312e310d0a486f73743a2031302e31302e34302e31343a393230300d0a436f6e6e656374696f6e3a206b6565702d616c6976650d0a43616368652d436f6e74726f6c3a206d61782d6167653d300d0a557067726164652d496e7365637572652d52657175657374733a20310d0a557365722d4167656e743a204d6f7a696c6c612f352e30202857696e646f7773204e542031302e303b20574f57363429204170706c655765624b69742f3533372e333620284b48544d4c2c206c696b65204765636b6f29204368726f6d652f35342e302e323834302e3731205361666172692f3533372e33360d0a4163636570743a20746578742f68746d6c2c6170706c69636174696f6e2f7868746d6c2b786d6c2c6170706c69636174696f6e2f786d6c3b713d302e392c696d6167652f776562702c2a2f2a3b713d302e380d0a4163636570742d456e636f64696e673a20677a69702c206465666c6174652c20736463680d0a4163636570742d4c616e67756167653a2072752d52552c72753b713d302e382c656e2d55533b713d302e362c656e3b713d302e342c756b3b713d302e320d0a436f6f6b69653a205f5f52657175657374566572696669636174696f6e546f6b656e3d78757330394e494f326c592d517375414a4548754333597947437733466639773877726f64344b46674c705a67647871716c61576a6e53746b33616e696e6776354c39382d545977526e685f546d5050457a704146556571755351313b204153502e4e45545f53657373696f6e49643d68786963316d633565616b726c35746f306f7a613031316a3b202e41535058415554483d3645374636434645444133333638433336443636353831354439433144304246353935433942444334333730443930364336413645333837324637313732423037383533414432373236423439434532463446453632393041453442423039443030313930464639334542364139434232454332323932374342453942303939314133324637303744444244393235433741413142423446434134424531413944343834303044323135463941343733344439393333323634324539394638424431434445364635343334323545323438394444373343453137303341313846413631303031314331454536393041323631303433374530344135443232304143303437313544423b2075736572496e666f3d7b226e616d65223a22d091d180d0b8d0b3d0b8d0b4d0b020d0a1d0bbd0b0d0b2d0b020d09ed182d187d0b5d181d182d0b2d0be222c22656d61696c223a22736c6176612e62726967696461406e6978736f6c7574696f6e732e636f6d227d0d0a0d0a
        at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:857)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
What does it mean? And how can I fix it?
I have elasticsearch with version 2.4.1.
Thanks!

**Comment by sscarduzio** [comment]
are you sure you're connecting as https and not http?
