### ISSUE TITLE
Getting a 500 error on _cat/nodes and all other stats links on data nodes

### ISSUE THREAD

**Issue by Kuckkuck** [sscarduzio/elasticsearch-readonlyrest-plugin#157]
Hi,

I am using Elasticsearch 2.4.1 and your plugin in version 1.13.0. It's working fine on master and client nodes, but on every data node I get an internal server error 500 since using 1.13.0. 1.12.2 was working fine. Your is the stacktrace, which is produced. Any idea?

[][][][master@ccadmin=>org.elasticsearch.cluster.metadata.AliasMetaData@dbbb474f][master@ccadmin=>org.elasticsearch.cluster.metadata.AliasMetaData@dbbb474f][master@ccadmin=>org.elasticsearch.cluster.metadata.AliasMetaData@dbbb474f][master@ccadmin=>org.elasticsearch.cluster.metadata.AliasMetaData@dbbb474f][][master@ccadmin=>org.elasticsearch.cluster.metadata.AliasMetaData@dbbb474f][master@ccadmin=>org.elasticsearch.cluster.metadata.AliasMetaData@dbbb474f][master@ccadmin=>org.elasticsearch.cluster.metadata.AliasMetaData@dbbb474f][master@ccadmin=>org.elasticsearch.cluster.metadata.AliasMetaData@dbbb474f][][][][][][][][][][][][2017-01-25 08:04:21,246][WARN ][rest.suppressed          ] path: /_nodes/stats, params: {all=true}
java.lang.ClassCastException: org.elasticsearch.action.admin.cluster.node.stats.NodesStatsRequest cannot be cast to org.elasticsearch.action.admin.indices.alias.IndicesAliasesRequest
	at org.elasticsearch.plugin.readonlyrest.acl.RequestContext$3.run(RequestContext.java:263)
	at org.elasticsearch.plugin.readonlyrest.acl.RequestContext$3.run(RequestContext.java:256)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.elasticsearch.plugin.readonlyrest.acl.RequestContext.setIndices(RequestContext.java:255)
	at org.elasticsearch.plugin.readonlyrest.acl.blocks.rules.impl.IndicesRule.match(IndicesRule.java:54)
	at org.elasticsearch.plugin.readonlyrest.acl.blocks.Block.check(Block.java:149)
	at org.elasticsearch.plugin.readonlyrest.acl.ACL.check(ACL.java:74)
	at org.elasticsearch.plugin.readonlyrest.IndexLevelActionFilter.apply(IndexLevelActionFilter.java:100)
	at org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:64)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:170)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:144)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:85)
	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:52)
	at org.elasticsearch.rest.BaseRestHandler$HeadersAndContextCopyClient.doExecute(BaseRestHandler.java:88)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
.....

Thanks a lot and regards,

Olaf

**Comment by sscarduzio** [comment]
Hello @Kuckkuck I just fixed this, I'll release a new bugfix build 1.13.2 later this week with other changes. 
Really happy how fast this code is getting more and more stable. And thanks to you and other users that keep on reporting issues when you find them 🙌
