### ISSUE TITLE
ES 5.1.2 do not start after adding the readonlyrest config into yml file

### ISSUE THREAD

**Issue by nan008** [sscarduzio/elasticsearch-readonlyrest-plugin#160]
Hello,

I got the plugin from email you sent me and installed it as instructed. I added the snippet that I need which is kibana to elasticserch.yml and restarted. 

ES version 5.1.2
Kibana version 5.1.2
plugin I installed readonlyrest-1.13.1_es5.1.2.zip

yml file

```bash
network.host: 10.0.200.107
http.port: 9200

http.type: ssl_netty4
readonlyrest:
enable: true
ssl:
enable: true
keystore_file: "/etc/elasticsearch/keystore.jks"
keystore_pass: changeit
key_pass: kibana
- name: Kibana Server
auth_key: kibana:kibana
type: allow
action.auto_create_index: true
http.cors.enabled: true
http.cors.allow-origin: "*"
script.inline: true
script.stored: true
```

```bash
Jan 27 16:18:33 localhost elasticsearch: Exception in thread "main" ElasticsearchParseException[null-valued setting found for key [readonlyrest] found at line number [89], column number [14]]
Jan 27 16:18:33 localhost elasticsearch: at org.elasticsearch.common.settings.loader.XContentSettingsLoader.serializeValue(XContentSettingsLoader.java:168)
Jan 27 16:18:33 localhost elasticsearch: at org.elasticsearch.common.settings.loader.XContentSettingsLoader.serializeObject(XContentSettingsLoader.java:110)
Jan 27 16:18:33 localhost elasticsearch: at org.elasticsearch.common.settings.loader.XContentSettingsLoader.load(XContentSettingsLoader.java:72)
Jan 27 16:18:33 localhost elasticsearch: at org.elasticsearch.common.settings.loader.XContentSettingsLoader.load(XContentSettingsLoader.java:50)
Jan 27 16:18:33 localhost elasticsearch: at org.elasticsearch.common.settings.loader.YamlSettingsLoader.load(YamlSettingsLoader.java:50)
Jan 27 16:18:33 localhost elasticsearch: at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:938)
Jan 27 16:18:33 localhost elasticsearch: at org.elasticsearch.common.settings.Settings$Builder.loadFromPath(Settings.java:927)
Jan 27 16:18:33 localhost elasticsearch: at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:102)
Jan 27 16:18:33 localhost elasticsearch: at org.elasticsearch.bootstrap.Bootstrap.initialEnvironment(Bootstrap.java:230)
Jan 27 16:18:33 localhost elasticsearch: at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
Jan 27 16:18:33 localhost elasticsearch: at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121)
Jan 27 16:18:33 localhost elasticsearch: at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112)
Jan 27 16:18:33 localhost elasticsearch: at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
Jan 27 16:18:33 localhost elasticsearch: at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
Jan 27 16:18:33 localhost elasticsearch: at org.elasticsearch.cli.Command.main(Command.java:88)
Jan 27 16:18:33 localhost elasticsearch: at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89)
Jan 27 16:18:33 localhost elasticsearch: at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82)
Jan 27 16:18:33 localhost elasticsearch: Refer to the log for complete error details.
Jan 27 16:18:33 localhost systemd: elasticsearch.service: main process exited, code=exited, status=1/FAILURE
Jan 27 16:18:33 localhost systemd: Unit elasticsearch.service entered failed state.
Jan 27 16:18:33 localhost systemd: elasticsearch.service failed.
```

But when I comment out the readonlyrest config, my node isstarting without problems, just saying that the plugin is disabled.

```bash
[2017-01-27T16:39:05,455][INFO ][o.e.p.PluginsService     ] [sys_elastic_node-01] loaded module [transport-netty3]
[2017-01-27T16:39:05,455][INFO ][o.e.p.PluginsService     ] [sys_elastic_node-01] loaded module [transport-netty4]
[2017-01-27T16:39:05,456][INFO ][o.e.p.PluginsService     ] [sys_elastic_node-01] loaded plugin [readonlyrest]
[2017-01-27T16:39:07,371][INFO ][o.e.p.r.ConfigurationHelper] SSL: Disabled
[2017-01-27T16:39:07,371][INFO ][o.e.p.r.IndexLevelActionFilter] [sys_elastic_node-01] Readonly REST plugin was loaded...
[2017-01-27T16:39:07,371][INFO ][o.e.p.r.IndexLevelActionFilter] [sys_elastic_node-01] Readonly REST plugin is disabled!
[2017-01-27T16:39:07,719][INFO ][o.e.n.Node               ] [sys_elastic_node-01] initialized
[2017-01-27T16:39:07,720][INFO ][o.e.n.Node               ] [sys_elastic_node-01] starting ...
```

All I want to do is to allow users to login to Kibana with different read only access to the indices. Obviously I am missing something.

**Comment by nan008** [comment]
Hi,

kibana.yml

```bash
server.host: "10.0.200.104"
elasticsearch.url: "https://10.0.200.107:9200"
elasticsearch.username: "kibana"
elasticsearch.password: "kibana"
```

tried your settings (I have to comment out the netty4 as it is failing - log below)

```bash

cluster.name: sys_elastic_cluster-02
network.host: 10.0.200.107
http.port: 9200
#http.type: ssl_netty4
readonlyrest:
    enable: true

    ssl:
      enable: true
      keystore_file: "/etc/elasticsearch/keystore.jks"
      keystore_pass: changeit
      key_pass: kibana

    response_if_req_forbidden: Forbidden by ReadonlyREST ES plugin

    access_control_rules:
    - name: Kibana Server
      type: allow
      auth_key: kibana:kibana

    - name: Developer
      auth_key: dev:dev
      type: allow
      kibana_access: ro
      indices: ["<no-index>", ".kibana*", "default"]
```
without netty4 config

```bash
[2017-01-27T17:36:03,930][INFO ][o.e.n.Node               ] [] initializing ...
[2017-01-27T17:36:04,003][INFO ][o.e.e.NodeEnvironment    ] [A8npsb3] using [1] data paths, mounts [[/mnt/storage (/dev/xvdb)]], net usable_space [1.6tb], net total_space [1.6tb], spins? [no], types [xfs]
[2017-01-27T17:36:04,004][INFO ][o.e.e.NodeEnvironment    ] [A8npsb3] heap size [1.9gb], compressed ordinary object pointers [true]
[2017-01-27T17:36:04,005][INFO ][o.e.n.Node               ] node name [A8npsb3] derived from node ID [A8npsb3DS8S0Cc_xSLp8WA]; set [node.name] to override
[2017-01-27T17:36:04,007][INFO ][o.e.n.Node               ] version[5.1.2], pid[21664], build[c8c4c16/2017-01-11T20:18:39.146Z], OS[Linux/3.10.0-327.36.3.el7.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_111/25.111-b15]
[2017-01-27T17:36:04,743][INFO ][o.e.p.PluginsService     ] [A8npsb3] loaded module [aggs-matrix-stats]
[2017-01-27T17:36:04,743][INFO ][o.e.p.PluginsService     ] [A8npsb3] loaded module [ingest-common]
[2017-01-27T17:36:04,743][INFO ][o.e.p.PluginsService     ] [A8npsb3] loaded module [lang-expression]
[2017-01-27T17:36:04,743][INFO ][o.e.p.PluginsService     ] [A8npsb3] loaded module [lang-groovy]
[2017-01-27T17:36:04,743][INFO ][o.e.p.PluginsService     ] [A8npsb3] loaded module [lang-mustache]
[2017-01-27T17:36:04,743][INFO ][o.e.p.PluginsService     ] [A8npsb3] loaded module [lang-painless]
[2017-01-27T17:36:04,743][INFO ][o.e.p.PluginsService     ] [A8npsb3] loaded module [percolator]
[2017-01-27T17:36:04,743][INFO ][o.e.p.PluginsService     ] [A8npsb3] loaded module [reindex]
[2017-01-27T17:36:04,744][INFO ][o.e.p.PluginsService     ] [A8npsb3] loaded module [transport-netty3]
[2017-01-27T17:36:04,744][INFO ][o.e.p.PluginsService     ] [A8npsb3] loaded module [transport-netty4]
[2017-01-27T17:36:04,744][INFO ][o.e.p.PluginsService     ] [A8npsb3] loaded plugin [readonlyrest]
[2017-01-27T17:36:06,777][INFO ][o.e.p.r.a.ACL            ] ADDING readonlyrest Rules Block :: { name: 'Kibana Server', policy: ALLOW}
[2017-01-27T17:36:06,778][INFO ][o.e.p.r.a.ACL            ] ADDING readonlyrest Rules Block :: { name: 'Developer', policy: ALLOW}
[2017-01-27T17:36:06,778][INFO ][o.e.p.r.ConfigurationHelper] SSL: Enabled
[2017-01-27T17:36:06,778][INFO ][o.e.p.r.IndexLevelActionFilter] [A8npsb3] Readonly REST plugin was loaded...
[2017-01-27T17:36:06,778][INFO ][o.e.p.r.IndexLevelActionFilter] [A8npsb3] Readonly REST plugin is enabled. Yay, ponies!
[2017-01-27T17:36:07,015][INFO ][o.e.n.Node               ] initialized
[2017-01-27T17:36:07,015][INFO ][o.e.n.Node               ] [A8npsb3] starting ...
[2017-01-27T17:36:07,177][INFO ][o.e.t.TransportService   ] [A8npsb3] publish_address {10.0.200.107:9300}, bound_addresses {10.0.200.107:9300}
[2017-01-27T17:36:07,182][INFO ][o.e.b.BootstrapCheck     ] [A8npsb3] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
[2017-01-27T17:36:10,268][INFO ][o.e.c.s.ClusterService   ] [A8npsb3] new_master {A8npsb3}{A8npsb3DS8S0Cc_xSLp8WA}{TJFA9FSZSm2uubMDYCpqSA}{10.0.200.107}{10.0.200.107:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-01-27T17:36:10,287][INFO ][o.e.h.HttpServer         ] [A8npsb3] publish_address {10.0.200.107:9200}, bound_addresses {10.0.200.107:9200}
[2017-01-27T17:36:10,287][INFO ][o.e.n.Node               ] [A8npsb3] started
[2017-01-27T17:36:10,303][INFO ][o.e.g.GatewayService     ] [A8npsb3] recovered [0] indices into cluster_state
[2017-01-27T17:36:11,418][INFO ][o.e.p.r.a.ACL            ]  no block has matched, forbidding by default: { ID:c14ae9531db24982bc51b4a02a612421, TYP:GetIndexRequest, USR:null, BRS:false, ACT:indices:admin/get, OA:10.0.200.104, IDX:bad-request, MET:GET, PTH:/bad-request, CNT:<OMITTED, LENGTH=0>, HDR:, EFF:0, HIS:[Kibana Server->[auth_key->false]], [Developer->[kibana_access->true, indices->true, auth_key->false]] }
[2017-01-27T17:36:11,419][INFO ][o.e.p.r.IndexLevelActionFilter] [A8npsb3] forbidden request: { ID:c14ae9531db24982bc51b4a02a612421, TYP:GetIndexRequest, USR:null, BRS:false, ACT:indices:admin/get, OA:10.0.200.104, IDX:bad-request, MET:GET, PTH:/bad-request, CNT:<OMITTED, LENGTH=0>, HDR:, EFF:0, HIS:[Kibana Server->[auth_key->false]], [Developer->[kibana_access->true, indices->true, auth_key->false]] } Reason: null (null)
[2017-01-27T17:36:13,942][INFO ][o.e.p.r.a.ACL            ]  no block has matched, forbidding by default: { ID:493c0ff6928d4be1b1b629c10197de74, TYP:GetIndexRequest, USR:null, BRS:false, ACT:indices:admin/get, OA:10.0.200.104, IDX:bad-request, MET:GET, PTH:/bad-request, CNT:<OMITTED, LENGTH=0>, HDR:, EFF:0, HIS:[Kibana Server->[auth_key->false]], [Developer->[kibana_access->true, indices->true, auth_key->false]] }
[2017-01-27T17:36:13,942][INFO ][o.e.p.r.IndexLevelActionFilter] [A8npsb3] forbidden request: { ID:493c0ff6928d4be1b1b629c10197de74, TYP:GetIndexRequest, USR:null, BRS:false, ACT:indices:admin/get, OA:10.0.200.104, IDX:bad-request, MET:GET, PTH:/bad-request, CNT:<OMITTED, LENGTH=0>, HDR:, EFF:0, HIS:[Kibana Server->[auth_key->false]], [Developer->[kibana_access->true, indices->true, auth_key->false]] } Reason: null (null)
```

with netty4 activated:

```bash
[2017-01-27T17:39:31,190][INFO ][o.e.n.Node               ] [] initializing ...
[2017-01-27T17:39:31,250][INFO ][o.e.e.NodeEnvironment    ] [A8npsb3] using [1] data paths, mounts [[/mnt/storage (/dev/xvdb)]], net usable_space [1.6tb], net total_space [1.6tb], spins? [no], types [xfs]
[2017-01-27T17:39:31,250][INFO ][o.e.e.NodeEnvironment    ] [A8npsb3] heap size [1.9gb], compressed ordinary object pointers [true]
[2017-01-27T17:39:31,251][INFO ][o.e.n.Node               ] node name [A8npsb3] derived from node ID [A8npsb3DS8S0Cc_xSLp8WA]; set [node.name] to override
[2017-01-27T17:39:31,253][INFO ][o.e.n.Node               ] version[5.1.2], pid[21753], build[c8c4c16/2017-01-11T20:18:39.146Z], OS[Linux/3.10.0-327.36.3.el7.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_111/25.111-b15]
[2017-01-27T17:39:32,031][INFO ][o.e.p.PluginsService     ] [A8npsb3] loaded module [aggs-matrix-stats]
[2017-01-27T17:39:32,031][INFO ][o.e.p.PluginsService     ] [A8npsb3] loaded module [ingest-common]
[2017-01-27T17:39:32,031][INFO ][o.e.p.PluginsService     ] [A8npsb3] loaded module [lang-expression]
[2017-01-27T17:39:32,031][INFO ][o.e.p.PluginsService     ] [A8npsb3] loaded module [lang-groovy]
[2017-01-27T17:39:32,031][INFO ][o.e.p.PluginsService     ] [A8npsb3] loaded module [lang-mustache]
[2017-01-27T17:39:32,031][INFO ][o.e.p.PluginsService     ] [A8npsb3] loaded module [lang-painless]
[2017-01-27T17:39:32,031][INFO ][o.e.p.PluginsService     ] [A8npsb3] loaded module [percolator]
[2017-01-27T17:39:32,031][INFO ][o.e.p.PluginsService     ] [A8npsb3] loaded module [reindex]
[2017-01-27T17:39:32,031][INFO ][o.e.p.PluginsService     ] [A8npsb3] loaded module [transport-netty3]
[2017-01-27T17:39:32,031][INFO ][o.e.p.PluginsService     ] [A8npsb3] loaded module [transport-netty4]
[2017-01-27T17:39:32,032][INFO ][o.e.p.PluginsService     ] [A8npsb3] loaded plugin [readonlyrest]
[2017-01-27T17:39:33,419][INFO ][o.e.p.r.ConfigurationHelper] SSL: Enabled
[2017-01-27T17:39:33,445][INFO ][o.e.p.r.SSLTransportNetty4] [A8npsb3] creating SSL transport
[2017-01-27T17:39:33,954][INFO ][o.e.p.r.a.ACL            ] ADDING readonlyrest Rules Block :: { name: 'Kibana Server', policy: ALLOW}
[2017-01-27T17:39:33,955][INFO ][o.e.p.r.a.ACL            ] ADDING readonlyrest Rules Block :: { name: 'Developer', policy: ALLOW}
[2017-01-27T17:39:33,955][INFO ][o.e.p.r.ConfigurationHelper] SSL: Enabled
[2017-01-27T17:39:33,955][INFO ][o.e.p.r.IndexLevelActionFilter] [A8npsb3] Readonly REST plugin was loaded...
[2017-01-27T17:39:33,955][INFO ][o.e.p.r.IndexLevelActionFilter] [A8npsb3] Readonly REST plugin is enabled. Yay, ponies!
[2017-01-27T17:39:34,204][INFO ][o.e.n.Node               ] initialized
[2017-01-27T17:39:34,204][INFO ][o.e.n.Node               ] [A8npsb3] starting ...
[2017-01-27T17:39:34,321][INFO ][o.e.t.TransportService   ] [A8npsb3] publish_address {10.0.200.107:9300}, bound_addresses {10.0.200.107:9300}
[2017-01-27T17:39:34,326][INFO ][o.e.b.BootstrapCheck     ] [A8npsb3] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
[2017-01-27T17:39:37,411][INFO ][o.e.c.s.ClusterService   ] [A8npsb3] new_master {A8npsb3}{A8npsb3DS8S0Cc_xSLp8WA}{PD3Osm_dQDaLLzi5OfDbWA}{10.0.200.107}{10.0.200.107:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-01-27T17:39:37,461][INFO ][o.e.g.GatewayService     ] [A8npsb3] recovered [0] indices into cluster_state
[2017-01-27T17:39:37,567][INFO ][o.e.h.HttpServer         ] [A8npsb3] publish_address {10.0.200.107:9200}, bound_addresses {10.0.200.107:9200}
[2017-01-27T17:39:37,567][INFO ][o.e.n.Node               ] [A8npsb3] started
[2017-01-27T17:39:39,559][INFO ][o.e.p.r.SSLTransportNetty4] [A8npsb3] Initializing SSL channel...
[2017-01-27T17:39:39,572][WARN ][i.n.c.ChannelInitializer ] Failed to initialize a channel. Closing: [id: 0xc33d5bae, L:/10.0.200.107:9200 - R:/10.0.200.104:50340]
java.lang.NullPointerException: null
	at org.elasticsearch.plugin.readonlyrest.SSLTransportNetty4$SSLHandler.initChannel(SSLTransportNetty4.java:72) ~[readonlyrest-1.13.1_es5.1.2.jar:1.13.1_es5.1.2]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:419) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:478) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418) [netty-common-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:454) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [netty-common-4.1.6.Final.jar:4.1.6.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

```
I am complete newbie in ES, and need a bit of help with this

**Comment by sscarduzio** [comment]
How did you obtain/generate this file "/etc/elasticsearch/keystore.jks" ?

**Comment by nan008** [comment]
I generate it 

keytool -genkey -keyalg RSA -alias elastic -keystore keystore.jks -storepass password -validity 3602 -keysize 2048

**Comment by sscarduzio** [comment]
To debug when SSL gets stuck you could run Elasticsearch like this:

```bash 
export ES_JAVA_OPTS="-Djavax.net.debug=ssl"
bin/elasticsearch
```

**Comment by nan008** [comment]
Cannot run it as command line as I installed it from package and it meant to run as service:

```bash
[root@SYS_ELASTIC-BB elasticsearch]$ bin/elasticsearch -E  ES_JAVA_OPTS="-Djavax.net.debug=ssl"
Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/config
Likely root cause: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/config
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
```
Any config file that I can pass this on?

**Comment by sscarduzio** [comment]
what kind of package? A linux distribution?

**Comment by nan008** [comment]
yes, it is from yum repository

I have another test done trying to connect from kibana server with curl command

curl -XGET -k "https://10.0.200.107:9200/" (where -k is urn off curl's verification of the certificate)

This connection attempt is reflected in the elastic log with:

```bash
[2017-02-07T11:54:07,128][INFO ][o.e.p.r.SSLTransportNetty4] [A8npsb3] Initializing SSL channel...
[2017-02-07T11:54:07,277][INFO ][o.e.p.r.a.ACL            ]  no block has matched, forbidding by default: { ID:f27799006335476490c5a4cf054108bd, TYP:MainRequest, USR:null, BRS:true, ACT:cluster:monitor/main, OA:10.0.200.104, IDX:, MET:GET, PTH:/, CNT:<OMITTED, LENGTH=0>, HDR:User-Agent,content-length,Host,Accept, EFF:0, HIS:[Kibana Server->[auth_key->false]], [Accept all requests from filebeat->[hosts->false, auth_key->false]], [Developer->[kibana_access->false, indices->true, auth_key->false]] }
[2017-02-07T11:54:07,277][INFO ][o.e.p.r.IndexLevelActionFilter] [A8npsb3] forbidden request: { ID:f27799006335476490c5a4cf054108bd, TYP:MainRequest, USR:null, BRS:true, ACT:cluster:monitor/main, OA:10.0.200.104, IDX:, MET:GET, PTH:/, CNT:<OMITTED, LENGTH=0>, HDR:User-Agent,content-length,Host,Accept, EFF:0, HIS:[Kibana Server->[auth_key->false]], [Accept all requests from filebeat->[hosts->false, auth_key->false]], [Developer->[kibana_access->false, indices->true, auth_key->false]] } Reason: null (null)
```
So it is looking like the initializing the SSL channel is just waiting for connections from kibana/filebeat/logstash

**Comment by sscarduzio** [comment]
curl hangs too?

**Comment by nan008** [comment]
[root@SYS_KIBANA-01 ~]# curl -XGET -k "https://10.0.200.107:9200/"
Forbidden by ReadonlyREST ES plugin
[root@SYS_KIBANA-01 ~]#

**Comment by sscarduzio** [comment]
OK so it's working! Good! Makes sense if yours is a self signed certificate.
Now you say Kibana daemon doesn't manage to get responses? There's a configuration for doing the same as -k in curl in conf/kibana.yml

**Comment by nan008** [comment]
found it 

elasticsearch.ssl.verify: false

and also now kibana is connecting with no problem and prompting for password twice. Now need to figure out logstash and filebeat connection so it will actually send the logs to ES and I am good as gold.

**Comment by nan008** [comment]
Now, I need help connecting with logstash - do you want me to continue here or open new issue?

**Comment by nan008** [comment]
Hey, I figure it out and it is now working from filebeat via logstash and ES to Kibana

So YAY Ponies

I can write up my scenario for you if you want

**Comment by sscarduzio** [comment]
I'd so love if you do that. We need good material inside the forum! https://forum.readonlyrest.com 
There's a GitHub login and a "Cookbook Guides" category just for this kind of stuff :)

YAY Ponies indeed 😁 🦄

**Comment by nan008** [comment]
will do :)
