### ISSUE TITLE
SSL enabling is resulting in "java.security.SecurityPermission" errors

### ISSUE THREAD

**Issue by sudhishkr** [sscarduzio/elasticsearch-readonlyrest-plugin#248]
I have this as my configuration : 
```
#http.type: ssl_netty4
readonlyrest:
    enable: true
    #ssl:
    #  enable: true
    #  keystore_file: "/usr/share/elasticsearch/plugins/readonlyrest/keystore.jks"
    #  keystore_pass: readonlyrest
    #  key_pass: readonlyrest

    response_if_req_forbidden: "Forbidden by ReadonlyREST ES plugin"

    access_control_rules:

        - name: "::LOGSTASH::"
          type: allow
          auth_key: foo:foo
          actions: ["cluster:monitor/main","indices:admin/types/exists","indices:data/read/*","indices:data/write/*","indices:admin/template/*","indices:admin/create"]
          indices: ["twitter"]
```

This works in its current state for me.

But when I uncomment the `#ssl` & `#http.type: ssl_netty4` sections. And restart elasticsearch I get this big error trace.
```
Stopping elasticsearch:                                    [FAILED]
Starting elasticsearch: java.security.AccessControlException: access denied ("java.security.SecurityPermission" "getProperty.ssl.KeyManagerFactory.algorithm")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.security.Security.getProperty(Security.java:760)
	at org.jboss.netty.handler.ssl.JdkSslServerContext.<init>(JdkSslServerContext.java:134)
	at org.jboss.netty.handler.ssl.SslContext.newServerContext(SslContext.java:194)
	at org.jboss.netty.handler.ssl.SslContext.newServerContext(SslContext.java:99)
	at org.elasticsearch.plugin.readonlyrest.SSLContextProvider$2.run(SSLContextProvider.java:144)
	at org.elasticsearch.plugin.readonlyrest.SSLContextProvider$2.run(SSLContextProvider.java:136)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.elasticsearch.plugin.readonlyrest.SSLContextProvider.<init>(SSLContextProvider.java:135)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
```

Now this is resulting in a few issues related to getting access to the api's.

I verified the permissions on all the configuration files and elasticsearch folders. I also set the jvmoptions `export ES_JAVA_OPTS="-Dlog4j2.disable.jmx=true"`. (these are somethings I got fom my google searches).

Anyone have any idea around this?

**Comment by sscarduzio** [comment]
We had a similar case here:
https://forum.readonlyrest.com/t/simple-ssl-setup-on-windows/195/6

As you can see, this misleading error message can hide a "file not found" or filesystem permissions problem.

**Comment by sscarduzio** [comment]
Did you resolve @sudhishkr ?

**Comment by gulassi** [comment]
I got the same error but different stack trace. Using version 2.4.5 of elasticsearch.

```
Aug  9 12:36:06 cloud-cli elasticsearch: [2017-08-09 12:36:06,158][ERROR][plugin.readonlyrest.es   ] [Black Death] Failed to load SSL CertChain & private key from Keystore!
Aug  9 12:36:06 cloud-cli elasticsearch: java.security.AccessControlException: access denied ("java.security.SecurityPermission" "getProperty.ssl.KeyManagerFactory.algorithm")
Aug  9 12:36:06 cloud-cli elasticsearch: at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
Aug  9 12:36:06 cloud-cli elasticsearch: at java.security.AccessController.checkPermission(AccessController.java:884)
Aug  9 12:36:06 cloud-cli elasticsearch: at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
Aug  9 12:36:06 cloud-cli elasticsearch: at java.security.Security.getProperty(Security.java:760)
Aug  9 12:36:06 cloud-cli elasticsearch: at org.jboss.netty.handler.ssl.JdkSslServerContext.<init>(JdkSslServerContext.java:134)
Aug  9 12:36:06 cloud-cli elasticsearch: at org.jboss.netty.handler.ssl.SslContext.newServerContext(SslContext.java:194)
Aug  9 12:36:06 cloud-cli elasticsearch: at org.jboss.netty.handler.ssl.SslContext.newServerContext(SslContext.java:99)
Aug  9 12:36:06 cloud-cli elasticsearch: at org.elasticsearch.plugin.readonlyrest.es.SSLTransport$HttpSslChannelPipelineFactory.lambda$new$0(SSLTransport.java:66)
Aug  9 12:36:06 cloud-cli elasticsearch: at org.elasticsearch.plugin.readonlyrest.SSLCertParser.lambda$createContext$0(SSLCertParser.java:111)
Aug  9 12:36:06 cloud-cli elasticsearch: at java.security.AccessController.doPrivileged(Native Method)
Aug  9 12:36:06 cloud-cli elasticsearch: at org.elasticsearch.plugin.readonlyrest.SSLCertParser.createContext(SSLCertParser.java:109)
Aug  9 12:36:06 cloud-cli elasticsearch: at org.elasticsearch.plugin.readonlyrest.SSLCertParser.<init>(SSLCertParser.java:41)
Aug  9 12:36:06 cloud-cli elasticsearch: at org.elasticsearch.plugin.readonlyrest.es.SSLTransport$HttpSslChannelPipelineFactory.<init>(SSLTransport.java:60)
Aug  9 12:36:06 cloud-cli elasticsearch: at org.elasticsearch.plugin.readonlyrest.es.SSLTransport.configureServerChannelPipelineFactory(SSLTransport.java:51)
Aug  9 12:36:06 cloud-cli elasticsearch: at org.elasticsearch.http.netty.NettyHttpServerTransport.doStart(NettyHttpServerTransport.java:257)
Aug  9 12:36:06 cloud-cli elasticsearch: at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
Aug  9 12:36:06 cloud-cli elasticsearch: at org.elasticsearch.http.HttpServer.doStart(HttpServer.java:107)
Aug  9 12:36:06 cloud-cli elasticsearch: at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
Aug  9 12:36:06 cloud-cli elasticsearch: at org.elasticsearch.node.Node.start(Node.java:289)
Aug  9 12:36:06 cloud-cli elasticsearch: at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:222)
Aug  9 12:36:06 cloud-cli elasticsearch: at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:288)
Aug  9 12:36:06 cloud-cli elasticsearch: at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:45)
```

Managed to get ssl working by inserting the failing permission as a default permission in global policy file: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.141-1.b16.el7_3.x86_64/jre/lib/security/java.policy, but I guess that isn't very secure way to go about fixing this.

**Comment by sscarduzio** [comment]
Yes in 2.x there is an issue because ES does not read the plugin permissions file. And this makes SSL fail, as you noticed.

Your solution is good, but you could have also told the ES  process to use the plugin's permission property file globally to the ES process (rather than globally to the whole JVM installation).

**Comment by sudhishkr** [comment]
Yeahp @sscarduzio - i needed this fix : 

```

**Comment by sudhishkr** [comment]
also - during the manual installation - i hit a few issues due to permissions, as i was root. the right user for the installation of this should be `elasticsearch`. (i guess folks here would know this, but something i struggled with because the errors don't clearly indicate it was a user perm problem)

Also i have a working puppet module, to install RoR with ES, and i can write up an ansible one if required. @sscarduzio - i guess having a puppet / ansible sample will make life easy for installs - what are your thoughts?

**Comment by sscarduzio** [comment]
Awesome, yeah please tell us about how you used puppet (I don't know anything about puppet, quite curious). 
We have a forum section just for that: https://forum.readonlyrest.com/c/cookbooks

**Comment by Ark74** [comment]
Have any body tried `update-ca-certificates -f` ?
