### ISSUE TITLE
Error during ES start, with plugin RoR

### ISSUE THREAD

**Issue by sudhishkr** [sscarduzio/elasticsearch-readonlyrest-plugin#257]
I have built the plugin locally, and tried installing it. This process seemed to work till about recently.

Last few days I am seeing this issue : 

```
[root@elasticsearch-logsascratchbtest_es_l-364-ascratchb skasabar]# /etc/init.d/elasticsearch start
Starting elasticsearch: Exception in thread "main" java.lang.UnsupportedClassVersionError: org/elasticsearch/plugin/readonlyrest/ReadonlyRestPlugin : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:786)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:463)
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:431)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:129)
	at org.elasticsearch.node.Node.<init>(Node.java:158)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)

**Comment by sudhishkr** [comment]
I am trying to understand if something changed w.r.t RoR code.

My installation steps were as follows : 

```
wget https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/archive/v1.13.3_es2.3.4.zip
unzip v1.13.3_es2.3.4.zip
cd v1.13.3_es2.3.4
brew install maven
sh bin/build.sh
cp the built zip file, and install using the command : /usr/share/elasticsearch/bin/plugin install file:///etc/elasticsearch/readonlyrest.zip

**Comment by sudhishkr** [comment]
From my google search I read that - this error is mostly due to a higher version compilation vs running on a lower version jdk.

I am not sure whats causing this issue. Could use a little help in understanding if something changed.

Also this was working abt 10days back.

**Comment by sudhishkr** [comment]
Also looking at this zip file, there seems to be no change. Is the code pulling something fromthe web that might have changed may be?

https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/releases/tag/v1.13.3_es2.3.4

**Comment by sudhishkr** [comment]
Its fine now, able to get past this.
