### ISSUE TITLE
"message":"socket hang up" in kibana logs

### ISSUE THREAD

**Issue by 1tarak** [sscarduzio/elasticsearch-readonlyrest-plugin#325]
Hi,

i am using elk v6.2.1 with readonlyREST
i am getting below error in the kibana logs continuously. Does any of you face a similar issue.
Here is is my kibana.yml and elasticsearch.yml file contents.
This occurs only when SSL is enabled on kibana Webserver 

**{"type":"error","@timestamp":"2018-03-23T07:29:15Z","tags":["connection","client","error"],"pid":21733,"level":"error","error":{"message":"socket hang up","name":"Error","stack":"Error: socket hang up\n    at TLSSocket.<anonymous> (_tls_wrap.js:847:25)\n    at emitOne (events.js:101:20)\n    at TLSSocket.emit (events.js:188:7)\n    at _handle.close (net.js:497:12)\n    at Socket.done (_tls_wrap.js:332:7)\n    at Socket.g (events.js:292:16)\n    at emitOne (events.js:101:20)\n    at Socket.emit (events.js:188:7)\n    at TCP._handle.close [as _onclose] (net.js:497:12)","code":"ECONNRESET"},"message":"socket hang up"}**

server.port: 5601
server.host: xxxxxxxxxxxxxxxxx
server.maxPayloadBytes: 10485760
elasticsearch.url: https://xxxxxxxxxxxxxx:9200
elasticsearch.pingTimeout: 4500
elasticsearch.requestTimeout: 180000
kibana.index: .kibana
logging.dest: kibana.log
elasticsearch.username: "kibana"
elasticsearch.password: "xxxxxx"
logging.verbose: true
elasticsearch.ssl.verificationMode: none
server.ssl.enabled: true
server.ssl.key: "keystore.key"
server.ssl.certificate: "appcertificate.crt"
server.ssl.keyPassphrase: xxxxxxxx

elasticsearch.yml

 cluster.name: testing
 node.name: client
 node.master: false
 node.data: false
 path.data: data
 path.logs: logs
 discovery.zen.ping.unicast.hosts: ["ms1","ms2","ms3"]
 network.host: xxxxxxxxxxxx
 http.port: 9200
 bootstrap.memory_lock: true
 thread_pool.bulk.queue_size : 2000
 http.type: ssl_netty4

**Comment by 1tarak** [comment]
The issue was with LTM. issue is resolved
