### ISSUE TITLE
[readonlyrest] is incompatible with version [6.2.3]; was designed for version [6.2.2]

### ISSUE THREAD

**Issue by approached** [sscarduzio/elasticsearch-readonlyrest-plugin#327]
root@indurena /usr/share/elasticsearch # bin/elasticsearch-plugin install file:/usr/share/elasticsearch/readonlyrest-1.16.17_es6.2.2.zip

-> Downloading file:/usr/share/elasticsearch/readonlyrest-1.16.17_es6.2.2.zip
[=================================================] 100%??
Exception in thread "main" java.lang.IllegalArgumentException: plugin [readonlyrest] is incompatible with version [6.2.3]; was designed for version [6.2.2]

**Comment by sscarduzio** [comment]
Missing 2 slashes 
```
file:///usr/share[...]
```

**Comment by sscarduzio** [comment]
Also, let me release the new version which is compatible with 6.2.3

**Comment by sscarduzio** [comment]
it's out!

**Comment by Happyfeet01** [comment]
Hello,

Have the same error. 

```
anel:/usr/share/elasticsearch# sudo bin/elasticsearch-plugin install file:rea
donlyrest-1.16.18_es6.2.3.zip                                                      
-> Downloading file:readonlyrest-1.16.18_es6.2.3.zip                               
[=================================================] 100%                           
Exception in thread "main" java.lang.IllegalArgumentException: plugin [ingest-attac
hment] is incompatible with version [6.2.3]; was designed for version [6.2.1]      
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:
237)                                                                               
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService
.java:349)                                                                         
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService
.java:328)                                                                         
        at org.elasticsearch.plugins.InstallPluginCommand.jarHellCheck(InstallPlugi
nCommand.java:600)                                                                 
        at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPlu
ginCommand.java:588)                                                               
        at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPlug
inCommand.java:707)                                                                
        at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginComm
and.java:623)                                                                      
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginComm
and.java:223)                                                                      
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginComm
and.java:212)                                                                      
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCo
mmand.java:86)                                                                     
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:75)        
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)                     
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:48)             
```

Which version is wrong? Elasticsearch or readonlyrest?

**Comment by sscarduzio** [comment]
Guys please read the docs:

[](https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md#installing)

As I said right above your comment, you need to use `file://` prefix. I.e. `bin/elasticsearch-plugin install  file:///some/path/readonlyrest-1.16.18_es6.2.3.zip`.
