### ISSUE TITLE
readonlyrest-plugin break "cluster status" plugins

### ISSUE THREAD

**Issue by danielmotaleite** [sscarduzio/elasticsearch-readonlyrest-plugin#33]
Trying to use the kopf plugin to check a 2 nodes ES setup, i get this:

```
Mar 28 21:17:48 ES1 elasticsearch[26307]: [2016-03-28 21:17:48,578][INFO ][rest.suppressed          ] /_nodes/stats/jvm,fs,os,process Params: {metric=jvm,fs,os,process}
Mar 28 21:17:48 ES1 elasticsearch[26307]: java.lang.ClassCastException: org.elasticsearch.action.admin.indices.stats.CommonStatsFlags cannot be cast to [Ljava.lang.String;
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.plugin.readonlyrest.acl.blocks.rules.impl.IndicesRule$1.run(IndicesRule.java:55)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.plugin.readonlyrest.acl.blocks.rules.impl.IndicesRule$1.run(IndicesRule.java:48)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at java.security.AccessController.doPrivileged(Native Method)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.plugin.readonlyrest.acl.blocks.rules.impl.IndicesRule.getIndices(IndicesRule.java:47)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.plugin.readonlyrest.acl.blocks.rules.impl.IndicesRule.match(IndicesRule.java:73)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.plugin.readonlyrest.acl.blocks.Block.check(Block.java:104)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.plugin.readonlyrest.acl.ACL.check(ACL.java:46)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.plugin.readonlyrest.IndexLevelActionFilter.apply(IndexLevelActionFilter.java:82)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:63)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:99)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:77)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:351)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:52)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.rest.BaseRestHandler$HeadersAndContextCopyClient.doExecute(BaseRestHandler.java:83)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:351)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:845)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.nodesStats(AbstractClient.java:940)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.rest.action.admin.cluster.node.stats.RestNodesStatsAction.handleRequest(RestNodesStatsAction.java:109)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:54)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.rest.RestController.executeHandler(RestController.java:207)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.rest.RestController$RestHandlerFilter.process(RestController.java:281)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.rest.RestController$ControllerFilterChain.continueProcessing(RestController.java:262)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.plugin.readonlyrest.ReadonlyRestAction$1.process(ReadonlyRestAction.java:39)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.rest.RestController$ControllerFilterChain.continueProcessing(RestController.java:265)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:176)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:128)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:86)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:385)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:63)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:60)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
Mar 28 21:17:48 ES1 elasticsearch[26307]: at java.lang.Thread.run(Thread.java:745)

```

Trying other plugins like the "Elastic HQ" also gave problems.
the request that fails is http://192.168.0.1:9200/_nodes/stats/jvm,fs,os,process

Other requests like `http://192.168.0.1:9200/_cluster/state/master_node,routing_table,blocks/ ` and `http://192.168.0.1:9200/_nodes/_all/os,jvm`  do work fine

Before installing the plugin, those "cluster status plugins" did work without any problem.

Thanks

**Comment by danielmotaleite** [comment]
`http://192.168.60.100:9200/_nodes/lgqV5l70QUG_aGH-N60CeQ/stats?all=1`  also fails

the http returns this:
```
{error: {root_cause: [{type: "class_cast_exception",…}], type: "class_cast_exception",…}, status: 500}
error: {root_cause: [{type: "class_cast_exception",…}], type: "class_cast_exception",…}
reason: "org.elasticsearch.action.admin.indices.stats.CommonStatsFlags cannot be cast to [Ljava.lang.String;"
root_cause: [{type: "class_cast_exception",…}]
type: "class_cast_exception"
status: 500
```

**Comment by sscarduzio** [comment]
I should definitely handle those exceptions. In the meanwhile I suggest you create another allow block with a `uri_re` rule that lets these requests go through. 

Thanks for reporting!

**Comment by danielmotaleite** [comment]
Strange, after another restart round of all elastic search nodes, it started to work fine, without any change!!

Maybe some browser cache that expired or node/cluster state that was shared between nodes, but it was something that got cleanup after a restart.

Thanks for the help and for the plugin.

for me this can be closed, i don't know if you want to keep this open to handle this exception later on.

**Comment by sscarduzio** [comment]
I made a new build (v1.9.0) that doesn't throw an exception when the request at hand refers to no indices (as in this example).
It's not yet possible to specify a behaviour for a specific class of actions (i.e. cluster:*). I probably need to create an "actions" rule soon and will have that and other things covered.

**Comment by danielmotaleite** [comment]
I think i also found why this was giving the error and the disappeared.

After a cluster restart, entering the kopf plugin will give errors about the nodes and cluster until the cluster is green and will fail totally... if i already have the kopf open and then restart the cluster, kopf will probably give errors in the background, but it will update the other fields, making it look as everything is working... and after the cluster is green, it will work as normal

so this might be a kopf (and other tools) bug, or just that your plugin is now logging those failed requests and without the plugin, they are just silently ignore?

Either way, the exception disappeared after the cluster is green, everything works.

**Comment by sscarduzio** [comment]
I saw kopf supports http basic auth,  why you're not using this feature?

On Thu, Mar 31, 2016 at 7:17 PM, Daniel Mota Leite <notifications@github.com

**Comment by danielmotaleite** [comment]
as the browser was asking the auth, i never bother to check how kopf do it!!  :)

i just enabled it and i will test

**Comment by sscarduzio** [comment]
@danielmotaleite any luck with authenticated Kopf?

**Comment by sdcharle** [comment]
I just tried kopf here. It prompted me to login...then I was good.

Thanks for this plugin. Kind of saved my bacon when management balked at the price of Shield.

**Comment by sscarduzio** [comment]
Thanks @sdcharle, glad to help. Apparently this thing saved a lot of people's bacon indeed. Proud of that.
Will close this issue.

**Comment by danielmotaleite** [comment]
Sorry about the delay
yes, just updated everything (full ELK stack+plugin) and everything is working fine. kopf after saving the auth do not give me errors any more

by the way, elasticsearch is now at 2.3.1 ... 
i had to updated the file /usr/share/elasticsearch/plugins/readonlyrest/plugin-descriptor.properties manually to 2.3.1   :smiley: 

Thanks a lot for the help and for the plugin

**Comment by sscarduzio** [comment]
Thanks for coming back on this one! I will make a new build today.

**Comment by sscarduzio** [comment]
@danielmotaleite Build released! 🚀  (see #45)

**Comment by dcoueron** [comment]
Hi everyone,

I can't manage to make Kopf and other cluster management plugins ([Elasticsearch-GUI](https://github.com/jettro/elasticsearch-gui) for instance) work with ReadOnlyREST.
It keeps asking me for a user/pass.

Could you please explain the settings you used to make it work ?

**Comment by sscarduzio** [comment]
@danielmotaleite would be really cool if you can share your experience! :)

**Comment by dcoueron** [comment]
I almost get what I need but I'm facing a strange behavior with the following settings :

    - name: Kibana Server
      type: allow
      auth_key: server:XXXXX

    - name: Kibana Admin (read write)
      type: allow
      kibana_access: rw
      auth_key: kibadmin:XXXXX

    - name: Elasticsearch Admin
      type: allow
      auth_key: esadmin:XXXXX

With this configuration. I try to log into 2 different ES admin plugins : Kopf and "Elasticsearch GUI".
I can log to Elasticsearch GUI with usernames : server AND esadmin.
But i can only log to Kopf with "server" username.

I can't understand why...

**Comment by sscarduzio** [comment]
![Fuck Browsers](https://giphy.com/gifs/frustrated-annoyed-smashed-4seT1wVx2CFX2)

**Comment by danielmotaleite** [comment]
I use this in elasticsearch:

```
# ADMIN
    - name: Accept admin user
      type: allow
      auth_key: admin:(password)
```

Then in kopf page, in the top right corner, i changed the server url to `http://admin:(password)@es-server:9200`

This should work. 
if something fails, try to clean the cache, reset the url to the clean kopf url and try again... 
kopf is always doing something in the background, so only really a clean full session will work, reusing one that failed somewhere will keep reusing the bad connection/config/cache and keeps nagging about the auth.

in your case, probably the esadmin user is reusing some bad cached data

Finally, make sure you applied the correct config to all the ES cluster. One bad config may put kopf and the other GUIs in a crazy loop

**Comment by sscarduzio** [comment]
@danielmotaleite well said, thanks. 
I'd add myself to the choir saying that when you're in a cluster environment all the configuration files and installed plugins should be identical, as readonly rest is not anymore working only on the REST interface (which is local), but on the internal ElasticSearch API and messages can be routed to any node.
