### ISSUE TITLE
JWT on 5.5.3, 	readonlyrest-1.16.18_es5.5.3.zip

### ISSUE THREAD

**Issue by chopchop505** [sscarduzio/elasticsearch-readonlyrest-plugin#334]
I tried implemented JWT authentication on 5.5.3, and I'm getting error:
```
unknown setting [readonlyrest.jwt.0.name] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.5.3.jar:5.5.3]
Caused by: java.lang.IllegalArgumentException: unknown setting [readonlyrest.jwt.0.name] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:293) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:256) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:139) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.node.Node.<init>(Node.java:343) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.node.Node.<init>(Node.java:244) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:232) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:232) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:351) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.5.3.jar:5.5.3]
	... 6 more
	Suppressed: java.lang.IllegalArgumentException: unknown setting [readonlyrest.jwt.0.signature_key] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
		at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:293) ~[
```
```
readonlyrest:
    enable: true
    prompt_for_basic_auth: false

    access_control_rules:
    - name: Container housekeeping is allowed
      type: allow
      auth_key: admin:container

    - name: Valid JWT token is present
      type: allow
      jwt_auth: "jwt1"

    - name: Valid JWT token is present in custom header
      type: allow
      jwt_auth: "jwt2"

    - name: Valid JWT token is present with roles
      type: allow
      jwt_auth:
        name: "jwt3"
        roles: ["role_viewer"]

  jwt:
    - name: jwt1
      signature_key: "123456"
      user_claim: user

    - name: jwt2
      header_name: x-custom-header
      signature_key: "123456"
      user_claim: user

    - name: jwt3
      signature_key: "123456789"
      user_claim: user
      roles_claim: roles
```

**Comment by chopchop505** [comment]
https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md

The documentation for JWT has the jwt on the same index as access_control_rules.
I copied and pasted that directly from a test file.  Here's the update version

**Comment by chopchop505** [comment]
```
readonlyrest:
    enable: true
    prompt_for_basic_auth: false

    access_control_rules:
    - name: Container housekeeping is allowed
      type: allow
      auth_key: admin:container

    - name: Valid JWT token is present
      type: allow
      jwt_auth: "jwt1"

    - name: Valid JWT token is present in custom header
      type: allow
      jwt_auth: "jwt2"

    - name: Valid JWT token is present with roles
      type: allow
      jwt_auth:
        name: "jwt3"
        roles: ["role_viewer"]

    jwt:
    - name: jwt1
      signature_key: "123456"
      user_claim: user

    - name: jwt2
      header_name: x-custom-header
      signature_key: "123456"
      user_claim: user

    - name: jwt3
      signature_key: "123456789"
      user_claim: user
      roles_claim: roles
```

**Comment by chopchop505** [comment]
Also, this file was the basis of my testing
https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/3e02049a4d887606c105dab70b5a0161e1a551f1/integration-tests/src/test/resources/jwt_auth/elasticsearch.yml

**Comment by sscarduzio** [comment]
Copy-pasted your last config and it works:

```
[2018-04-10T21:06:32,575][INFO ][t.b.r.e.IndexLevelActionFilter] [vIEzObW] Settings observer refreshing...
[2018-04-10T21:06:32,981][INFO ][t.b.r.a.ACL              ] ADDING BLOCK:	{ name: 'Container housekeeping is allowed', policy: ALLOW}
[2018-04-10T21:06:32,986][INFO ][t.b.r.a.ACL              ] ADDING BLOCK:	{ name: 'Valid JWT token is present', policy: ALLOW}
[2018-04-10T21:06:32,986][INFO ][t.b.r.a.ACL              ] ADDING BLOCK:	{ name: 'Valid JWT token is present in custom header', policy: ALLOW}
[2018-04-10T21:06:32,986][INFO ][t.b.r.a.ACL              ] ADDING BLOCK:	{ name: 'Valid JWT token is present with roles', policy: ALLOW}
```

Does it still not work for you?

**Comment by chopchop505** [comment]
No, not on 5.5.3.  Was that the version you tested on?

**Comment by sscarduzio** [comment]
I tested on the latest 6.2.3. But this should be common code. Will check.

**Comment by chopchop505** [comment]
Yes I just tried a fresh install and same thing.  Please let me know what you find

**Comment by sscarduzio** [comment]
are you adding this settings to elasticsearch.yml?

**Comment by sscarduzio** [comment]
that's deprecated, it has security risks especially for the JWT secrets and clear text passwords. We moved everything to `readonlyrest.yml`. 

I reproduce this issue only if I use the old way (settings in elasticsearch.yml). Which in general should not happen, but it's deprecated.

**Comment by chopchop505** [comment]
Yes, thanks I was adding to elasticsearch.yml since I was just upgradine.  Changing to `readonlyrest.yml`  works.  Thanks for the help
