### ISSUE TITLE
Keystore with multiple certificate entries fails to load

### ISSUE THREAD

**Issue by The-Yoda** [sscarduzio/elasticsearch-readonlyrest-plugin#349]
I have a keystore with 2 entries, trustedCertEntry and PrivateKeyEntry.

When I tried to use it with ROR it fails with following exception:
```
tech.beshu.ror.commons.settings.SettingsMalformedException: Private key not found in keystore for alias: xxx
	at tech.beshu.ror.commons.SSLCertParser.createContext(SSLCertParser.java:123)
	at tech.beshu.ror.commons.SSLCertParser.<init>(SSLCertParser.java:45)
	at tech.beshu.ror.es.SSLTransportNetty4$SSLHandler.<init>(SSLTransportNetty4.java:94)
	at tech.beshu.ror.es.SSLTransportNetty4.configureServerChannelHandler(SSLTransportNetty4.java:85)
```

**Comment by The-Yoda** [comment]
Looked into the code. There is a way to configure which alias to use in ssl settings using `key_alias`.
But it is not documented [here](https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md)

**Comment by sscarduzio** [comment]
@The-Yoda we can consider this closed thanks to your documentation PR. Correct?

**Comment by The-Yoda** [comment]
Yes, you can close this.

Referencing private key entry automatically might be more helpful though :)
