### ISSUE TITLE
Unsupported http.type [ssl_netty4]

### ISSUE THREAD

**Issue by TrevorMills** [sscarduzio/elasticsearch-readonlyrest-plugin#365]
I had X-Pack installed, but it's not installed anymore.  I followed [these instructions](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin#use-case-enable-https-globally) for setting up ReadOnlyRest ( v 1.16.19 ), with one difference.  My `readonlyrest.yml` file looks like:

```
    enable: true
    ssl:
      enable: true
      certchain_pem: "/etc/elasticsearch/certs/fullchain.pem"
      privkey_pem: "/etc/elasticsearch/certs/privkey.pem"
```

Those chain files are copied from Let's Encrypt.  

When I try to start Elasticsearch with `http.type: ssl_netty4` in `elasticsearch.yml`, I get this error.

```
[2018-05-24T14:09:09,461][ERROR][o.e.b.Bootstrap          ] Exception
java.lang.IllegalStateException: Unsupported http.type [ssl_netty4]
	at org.elasticsearch.common.network.NetworkModule.getHttpServerTransportSupplier(NetworkModule.java:194) ~[elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.node.Node.<init>(Node.java:440) ~[elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.node.Node.<init>(Node.java:246) ~[elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.2.3.jar:6.2.3]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.2.3.jar:6.2.3]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) [elasticsearch-6.2.3.jar:6.2.3]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) [elasticsearch-6.2.3.jar:6.2.3]
```

I've tried searching and I can't find any answers.  Do you have any ideas?  Many thanks.

**Comment by TrevorMills** [comment]
I apologize.  I'm an idiot.  

I had done everything except for installing the readonlyrest plugin, which I now understand is the thing that actually creates the `ssl_netty4` protocol.  

Sheesh.
