### ISSUE TITLE
missing java security permission ("java.lang.RuntimePermission" "setContextClassLoader")

### ISSUE THREAD

**Issue by usp-rol** [sscarduzio/elasticsearch-readonlyrest-plugin#397]
there has been already some reports about java security issues. tested on ES 6.5.0 with latest ROR 1.16.30 unless one manually adds

`permission java.lang.RuntimePermission "setContextClassLoader";`

to `/usr/share/elasticsearch/plugins/readonlyrest/plugin-security.policy` ES will not stop and hang (see below) once SSL is in use (`http.type: ssl_netty4`)

>[2018-12-05T11:21:38,772][INFO ][o.e.n.Node               ] [ZX4mXQm] stopping ...
[2018-12-05T11:21:38,782][ERROR][i.n.u.c.D.rejectedExecution] [ZX4mXQm] Failed to submit a listener notification task. Event loop shut down?
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "setContextClassLoader")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:?]
        at java.security.AccessController.checkPermission(AccessController.java:895) ~[?:?]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:322) ~[?:?]
        at java.lang.Thread.setContextClassLoader(Thread.java:1522) ~[?:?]
        at io.netty.util.concurrent.GlobalEventExecutor$2.run(GlobalEventExecutor.java:228) ~[netty-common-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.GlobalEventExecutor$2.run(GlobalEventExecutor.java:225) ~[netty-common-4.1.30.Final.jar:4.1.30.Final]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at io.netty.util.concurrent.GlobalEventExecutor.startThread(GlobalEventExecutor.java:225) ~[netty-common-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.GlobalEventExecutor.execute(GlobalEventExecutor.java:213) ~[netty-common-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:768) [netty-common-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:432) [netty-common-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:94) [netty-common-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:939) [netty-common-4.1.30.Final.jar:4.1.30.Final]
        at java.lang.Thread.run(Thread.java:834) [?:?]

it would be great if that fix could be implemented in the next version...

**Comment by usp-rol** [comment]
seems, this is not fixed in the next version as of tests today with 1.16.31 still shows the same behaviour:

> [2018-12-11T09:32:45,921][INFO ][o.e.n.Node               ] [U39KJhM] stopping ...
[2018-12-11T09:32:45,941][ERROR][i.n.u.c.D.rejectedExecution] [U39KJhM] Failed to submit a listener notification task. Event loop shut down?
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "setContextClassLoader")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:?]
        at java.security.AccessController.checkPermission(AccessController.java:895) ~[?:?]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:322) ~[?:?]
        at java.lang.Thread.setContextClassLoader(Thread.java:1522) ~[?:?]
        at io.netty.util.concurrent.GlobalEventExecutor$2.run(GlobalEventExecutor.java:228) ~[netty-common-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.GlobalEventExecutor$2.run(GlobalEventExecutor.java:225) ~[netty-common-4.1.30.Final.jar:4.1.30.Final]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at io.netty.util.concurrent.GlobalEventExecutor.startThread(GlobalEventExecutor.java:225) ~[netty-common-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.GlobalEventExecutor.execute(GlobalEventExecutor.java:213) ~[netty-common-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:768) [netty-common-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:432) [netty-common-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:94) [netty-common-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:939) [netty-common-4.1.30.Final.jar:4.1.30.Final]
        at java.lang.Thread.run(Thread.java:834) [?:?]


was there any re-planning to not include the fix in 1.16.31?

**Comment by usp-rol** [comment]
apologies...

testing was made on wrong branch. everything is fine with ROR 1.16.31 / ES 6.5.1, thanks!

>[2018-12-11T09:44:15,203][INFO ][o.e.n.Node               ] [1dBqc-w] stopping ...
[2018-12-11T09:44:15,238][INFO ][o.e.n.Node               ] [1dBqc-w] stopped
[2018-12-11T09:44:15,239][INFO ][o.e.n.Node               ] [1dBqc-w] closing ...
[2018-12-11T09:44:15,280][INFO ][t.b.r.c.s.e.ESShutdownObservable] [1dBqc-w] Shutting down ROR resources...
[2018-12-11T09:44:15,289][INFO ][t.b.r.c.s.SettingsPoller ] [1dBqc-w] Shutting down settings poller executor...
[2018-12-11T09:44:15,301][INFO ][o.e.n.Node               ] [1dBqc-w] closed
