### ISSUE TITLE
 Missing connection timeouts for ExternalAuthenticationServiceClient

### ISSUE THREAD

**Issue by lillesand** [sscarduzio/elasticsearch-readonlyrest-plugin#409]
I might be wrong here, but both from observed behavior and reading the code it appears that socket and connection timeouts are missing for the `ExternalAuthenticationServiceClient`. It appears to be set correctly for LDAP connections, but not for other external authentication services.

We've observed that after running ElasticSearch with ROR for about a week under moderately high load (nothing extreme, but definitely traffic), authentication stops working for some nodes in our cluster:

```
[2019-02-06T08:10:59,164][INFO ][t.b.r.h.ApacheHttpCoreClient] [servername] HTTP client failed to connect: [dce6ef35-f2c3-4700-a172-6f0bd2abcc41] GET https://full-hostname/api/auth reason: Connection closed
[2019-02-06T08:10:59,167][ERROR][t.b.r.a.b.Block          ] [servername] es_admins: external_authentication rule matching got an error org.apache.http.ConnectionClosedException: Connection closed
java.util.concurrent.CompletionException: org.apache.http.ConnectionClosedException: Connection closed
... massive stack trace ...
        at tech.beshu.ror.acl.definitions.externalauthenticationservices.ExternalAuthenticationServiceHttpClient.authenticate(ExternalAuthenticationServiceHttpClient.java:41) ~[?:?]
        at tech.beshu.ror.acl.definitions.externalauthenticationservices.CachedExternalAuthenticationServiceClient.authenticate(CachedExternalAuthenticationServiceClient.java:68) ~[?:?]
...
```

The external authentication service is running fine, but a once a node starts failing it doesn't recover before it's restarted.

To me this seems indicative of stale connections in the connection pool, and reading the code seems to confirm this.

**Comment by lillesand** [comment]
Working on a PR for this.

**Comment by lillesand** [comment]
Created PR at https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/pull/410

**Comment by sscarduzio** [comment]
@lillesand you PR satisfies this issue, right? Can close?

**Comment by lillesand** [comment]
Yup!

**Comment by lillesand** [comment]
Fixed.
