### ISSUE TITLE
NullPointerException when sending a PUT request

### ISSUE THREAD

**Issue by lucasmogari** [sscarduzio/elasticsearch-readonlyrest-plugin#419]
I'm getting a NPE when PUTing a template

ES: 6.7.0
Ror: 1.17.4-pre2_es6.7.0

Error:
```
[2019-03-29T13:10:46,252][INFO ][o.e.c.m.MetaDataIndexTemplateService] [d-qW6Ay] adding template [metricbeat-6.7.0] for index patterns [*-metricbeat-6.7.0-*]
[2019-03-29T13:10:53,149][WARN ][r.suppressed             ] [d-qW6Ay] path: /_template/metricbeat-6.7.0, params: {name=metricbeat-6.7.0}
java.lang.NullPointerException: value
	at io.netty.util.internal.ObjectUtil.checkNotNull(ObjectUtil.java:33) ~[?:?]
	at io.netty.handler.codec.DefaultHeaders.addObject(DefaultHeaders.java:327) ~[?:?]
	at io.netty.handler.codec.http.DefaultHttpHeaders.add(DefaultHttpHeaders.java:117) ~[?:?]
	at org.elasticsearch.http.netty4.Netty4HttpChannel.setHeaderField(Netty4HttpChannel.java:168) ~[?:?]
	at org.elasticsearch.http.netty4.Netty4HttpChannel.setHeaderField(Netty4HttpChannel.java:163) ~[?:?]
	at org.elasticsearch.http.netty4.Netty4HttpChannel.addCustomHeaders(Netty4HttpChannel.java:189) ~[?:?]
	at org.elasticsearch.http.netty4.Netty4HttpChannel.sendResponse(Netty4HttpChannel.java:113) ~[?:?]
	at org.elasticsearch.rest.RestController$ResourceHandlingHttpChannel.sendResponse(RestController.java:497) ~[elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.rest.action.RestResponseListener.processResponse(RestResponseListener.java:37) ~[elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.rest.action.RestActionListener.onResponse(RestActionListener.java:47) [elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:85) [elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:81) [elasticsearch-6.7.0.jar:6.7.0]
	at tech.beshu.ror.es.ResponseActionListener.onResponse(ResponseActionListener.java:54) [readonlyrest-1.17.4-pre2_es6.7.0.jar:?]
	at tech.beshu.ror.es.ResponseActionListener.onResponse(ResponseActionListener.java:29) [readonlyrest-1.17.4-pre2_es6.7.0.jar:?]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$1.onResponse(TransportMasterNodeAction.java:194) [elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$1.onResponse(TransportMasterNodeAction.java:191) [elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.action.admin.indices.template.put.TransportPutIndexTemplateAction$1.onResponse(TransportPutIndexTemplateAction.java:97) [elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.cluster.metadata.MetaDataIndexTemplateService$2.clusterStateProcessed(MetaDataIndexTemplateService.java:193) [elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.cluster.service.MasterService$SafeClusterStateTaskListener.clusterStateProcessed(MasterService.java:476) [elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.cluster.service.MasterService$TaskOutputs.lambda$processedDifferentClusterState$1(MasterService.java:363) [elasticsearch-6.7.0.jar:6.7.0]
	at java.util.ArrayList.forEach(ArrayList.java:1540) [?:?]
	at org.elasticsearch.cluster.service.MasterService$TaskOutputs.processedDifferentClusterState(MasterService.java:363) [elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:237) [elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:135) [elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) [elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-6.7.0.jar:6.7.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-6.7.0.jar:6.7.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

Debugging wihout ror, I found that io.netty.handler.codec.DefaultHeaders:327 receives this:
> {Warning=[299 Elasticsearch-6.7.0-8453f77 "[types removal] The parameter include_type_name should be explicitly specified in put template requests to prepare for 7.0. In 7.0 include_type_name will default to 'false', and requests are expected to omit the type name in mapping definitions."]}

With ror, it receives this:
> {Warning=[299 Elasticsearch-6.7.0-8453f77 "[types removal] The parameter include_type_name should be explicitly specified in put template requests to prepare for 7.0. In 7.0 include_type_name will default to 'false', and requests are expected to omit the type name in mapping definitions.", **null**], x-ror-username=[test]}

There's an extra item in the array with a null.

I think it's because of the code below. If you could point me where to fix this, I'd be glad to send a PR.

tech.beshu.ror.es.RequestInfo:
```
	@Override
	public void writeResponseHeaders(Map<String, String> hMap) {
		threadPool.getThreadContext().getResponseHeaders().keySet().stream()
				.forEach(k -> threadPool.getThreadContext().addResponseHeader(k, null, v -> null));
		hMap.keySet().forEach(k -> {
			String val = hMap.get(k);
			threadPool.getThreadContext().addResponseHeader(k, val, v -> val);
		});
	}

```

Thanks.

**Comment by lucasmogari** [comment]
I updated to 1.17.4-pre3_es6.7.0 and it's working. So I'm closing this.

Thanks.

**Comment by sscarduzio** [comment]
Yeah I know, the fix for this was not super obvious. Also that deprecation log in the response headers was super weird. I saw that too. I wonder if it even works in the vanilla ES without ROR.

**Comment by lucasmogari** [comment]
Without ROR worked. Thanks again.

**Comment by sscarduzio** [comment]
hey @lucasmogari FYI you were right about the writeResponseHeaders method being wrong. I removed the thread context stash fix (which caused issues with filter and fields rule in msearch requests) and removed the first part of the method where we tried to remove any existing response headers before writing them. 🙏

**Comment by lucasmogari** [comment]
Nice! Thank you!
