### ISSUE TITLE
ROR starting failure: tech.beshu.ror.exceptions$StartingFailureException: Cannot find any 'readonlyrest' section in settings

### ISSUE THREAD

**Issue by hebbaa** [sscarduzio/elasticsearch-readonlyrest-plugin#641]
I am trying ROR as mentioned in the doc:
https://github.com/beshu-tech/readonlyrest-docs/blob/master/multitenancy_guide.md

While doing so i am seeing below exception:

[2020-09-21T15:13:50,086][INFO ][t.b.r.b.Ror              ] [Admins-MacBook-Pro.local] Loading ReadonlyREST settings from index failed: cannot find index
[2020-09-21T15:13:50,087][INFO ][t.b.r.b.Ror              ] [Admins-MacBook-Pro.local] Loading ReadonlyREST settings from file: /Users/xxx/es/elasticsearch-7.8.1/config/readonlyrest.yml
[2020-09-21T15:13:50,115][ERROR][t.b.r.b.Ror              ] [Admins-MacBook-Pro.local] Loading ReadonlyREST from file failed: Cannot find any 'readonlyrest' section in settings
[2020-09-21T15:13:50,117][ERROR][t.b.r.e.IndexLevelActionFilter] [Admins-MacBook-Pro.local] ROR starting failure:
tech.beshu.ror.exceptions$StartingFailureException: Cannot find any 'readonlyrest' section in settings
	at tech.beshu.ror.exceptions$StartingFailureException$.from(exceptions.scala:35) ~[core-1.23.0.jar:?]
	at tech.beshu.ror.es.IndexLevelActionFilter.$anonfun$startRorInstance$3(IndexLevelActionFilter.scala:146) ~[readonlyrest-1.23.0_es7.8.1.jar:?]
	at tech.beshu.ror.es.IndexLevelActionFilter.$anonfun$startRorInstance$3$adapted(IndexLevelActionFilter.scala:141) ~[readonlyrest-1.23.0_es7.8.1.jar:?]
	at monix.execution.Callback$$anon$2.tryApply(Callback.scala:296) ~[monix-execution_2.12-3.0.0.jar:3.0.0]
	at monix.execution.Callback$$anon$2.apply(Callback.scala:289) ~[monix-execution_2.12-3.0.0.jar:3.0.0]
	at monix.execution.Callback$$anon$2.onSuccess(Callback.scala:285) ~[monix-execution_2.12-3.0.0.jar:3.0.0]
	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:165) ~[monix-eval_2.12-3.0.0.jar:3.0.0]
	at monix.eval.internal.TaskRestartCallback.syncOnSuccess(TaskRestartCallback.scala:101) ~[monix-eval_2.12-3.0.0.jar:3.0.0]
	at monix.eval.internal.TaskRestartCallback$$anon$1.run(TaskRestartCallback.scala:118) ~[monix-eval_2.12-3.0.0.jar:3.0.0]
	at monix.execution.internal.Trampoline.monix$execution$internal$Trampoline$$immediateLoop(Trampoline.scala:66) ~[monix-execution_2.12-3.0.0.jar:3.0.0]
	at monix.execution.internal.Trampoline.startLoop(Trampoline.scala:32) ~[monix-execution_2.12-3.0.0.jar:3.0.0]
	at monix.execution.schedulers.TrampolineExecutionContext$JVMNormalTrampoline.super$startLoop(TrampolineExecutionContext.scala:163) ~[monix-execution_2.12-3.0.0.jar:3.0.0]
	at monix.execution.schedulers.TrampolineExecutionContext$JVMNormalTrampoline.$anonfun$startLoop$1(TrampolineExecutionContext.scala:163) ~[monix-execution_2.12-3.0.0.jar:3.0.0]
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23) [scala-library-2.12.9.jar:?]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85) [scala-library-2.12.9.jar:?]
	at monix.execution.schedulers.TrampolineExecutionContext$JVMNormalTrampoline.startLoop(TrampolineExecutionContext.scala:163) [monix-execution_2.12-3.0.0.jar:3.0.0]
	at monix.execution.internal.Trampoline.execute(Trampoline.scala:40) [monix-execution_2.12-3.0.0.jar:3.0.0]
	at monix.execution.schedulers.TrampolineExecutionContext.execute(TrampolineExecutionContext.scala:64) [monix-execution_2.12-3.0.0.jar:3.0.0]
	at monix.execution.schedulers.BatchingScheduler.execute(BatchingScheduler.scala:50) [monix-execution_2.12-3.0.0.jar:3.0.0]
	at monix.execution.schedulers.BatchingScheduler.execute$(BatchingScheduler.scala:47) [monix-execution_2.12-3.0.0.jar:3.0.0]
	at monix.execution.schedulers.AsyncScheduler.execute(AsyncScheduler.scala:31) [monix-execution_2.12-3.0.0.jar:3.0.0]
	at monix.eval.internal.TaskRestartCallback.start(TaskRestartCallback.scala:56) [monix-eval_2.12-3.0.0.jar:3.0.0]
	at monix.eval.internal.TaskRunLoop$.executeAsyncTask(TaskRunLoop.scala:592) [monix-eval_2.12-3.0.0.jar:3.0.0]
	at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:120) [monix-eval_2.12-3.0.0.jar:3.0.0]
	at monix.eval.internal.TaskRestartCallback.syncOnError(TaskRestartCallback.scala:109) [monix-eval_2.12-3.0.0.jar:3.0.0]
	at monix.eval.internal.TaskRestartCallback.onError(TaskRestartCallback.scala:84) [monix-eval_2.12-3.0.0.jar:3.0.0]
	at monix.eval.internal.TaskRestartCallback.onError(TaskRestartCallback.scala:27) [monix-eval_2.12-3.0.0.jar:3.0.0]
	at monix.eval.internal.TaskExecuteOn$AsyncRegister$$anon$1.run(TaskExecuteOn.scala:70) [monix-eval_2.12-3.0.0.jar:3.0.0]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) [?:1.8.0_252]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_252]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_252]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_252]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_252]

Using  es version of 7.8.1
Using the readonlyrest.yml as mentioned in the doc:
 https://github.com/beshu-tech/readonlyrest-docs/blob/master/multitenancy_guide.md

**Comment by coutoPL** [comment]
```
[2020-09-21T15:13:50,087][INFO ][t.b.r.b.Ror ] [Admins-MacBook-Pro.local] Loading ReadonlyREST settings from file: /Users/xxx/es/elasticsearch-7.8.1/config/readonlyrest.yml
[2020-09-21T15:13:50,115][ERROR][t.b.r.b.Ror ] [Admins-MacBook-Pro.local] Loading ReadonlyREST from file failed: Cannot find any 'readonlyrest' section in settings
```

I see that ROR was trying to read `/Users/xxx/es/elasticsearch-7.8.1/config/readonlyrest.yml` and as the error message says there was no readonlyrest section in this yaml.

Please note that indentations are important
