### ISSUE TITLE
http://localhost:9200/_cat/shards gives a nullpointer exception

### ISSUE THREAD

**Issue by Kuckkuck** [sscarduzio/elasticsearch-readonlyrest-plugin#76]
Hi,

running on elasticsearch-readonlyrest-v1.9.3_es-v2.3.2 and elasticsearch 2.3.2. When opening http://localhost:9200/_cat/shardes gives me a {"error":{"root_cause":[{"type":"null_pointer_exception","reason":null}],"type":"null_pointer_exception","reason":null},"status":500}

and a stack trace:

[2016-06-16 09:13:23,596][WARN ][rest.suppressed          ] /_cat/shards Params: {}
java.lang.NullPointerException
	at org.elasticsearch.plugin.readonlyrest.acl.RequestContext.toString(RequestContext.java:138)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.elasticsearch.plugin.readonlyrest.acl.ACL.check(ACL.java:44)
	at org.elasticsearch.plugin.readonlyrest.IndexLevelActionFilter.apply(IndexLevelActionFilter.java:82)
	at org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:64)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:170)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:144)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:85)
	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.client.FilterClient.doExecute(FilterClient.java:52)
	at org.elasticsearch.rest.BaseRestHandler$HeadersAndContextCopyClient.doExecute(BaseRestHandler.java:83)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1226)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.stats(AbstractClient.java:1546)
	at org.elasticsearch.rest.action.cat.RestShardsAction$1.processResponse(RestShardsAction.java:73)
	at org.elasticsearch.rest.action.cat.RestShardsAction$1.processResponse(RestShardsAction.java:68)
	at org.elasticsearch.rest.action.support.RestActionListener.onResponse(RestActionListener.java:49)
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:89)
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:85)
	at org.elasticsearch.action.support.TransportAction$ResponseFilterChain.proceed(TransportAction.java:212)
	at org.elasticsearch.action.support.ActionFilter$Simple.apply(ActionFilter.java:78)
	at org.elasticsearch.action.support.TransportAction$ResponseFilterChain.proceed(TransportAction.java:210)
	at org.elasticsearch.action.support.TransportAction$FilteredActionListener.onResponse(TransportAction.java:237)
	at org.elasticsearch.action.support.TransportAction$FilteredActionListener.onResponse(TransportAction.java:223)
	at org.elasticsearch.action.support.ThreadedActionListener$1.doRun(ThreadedActionListener.java:89)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

my elasticsearch readonly config:

readonlyrest:
    enable: true
    response_if_req_forbidden: <h1>Forbidden</h1>    
    access_control_rules:

    - name: Admin (read write)
      type: allow
      kibana_access: rw
      auth_key: user:user

    - name: data
      type: allow
      auth_key: data:data

any idea, what I did wrong?

Regards

Olaf

**Comment by Kuckkuck** [comment]
any idea, why I get a null pointer?

**Comment by sscarduzio** [comment]
@Kuckkuck sorry for the delay: any chance to reproduce this with the new [elasticsearch-readonlyrest-v1.9.2_es-v2.3.4.zip](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.2_es-v2.3.4.zip?raw=true) build?

Because I couldn't!

**Comment by sistemasokn** [comment]
Thanks so much sscarduzio

**Comment by Kuckkuck** [comment]
I am still on EL 2.3.3 and plugin 1.9.3, because elasticsearch-cloud-kubernetes plugin isn't released for 2.3.4.

**Comment by sscarduzio** [comment]
you got it! see /download folder

**Comment by Kuckkuck** [comment]
works great, thanks a lot.
