### ISSUE TITLE
Problems with readonly plugin and topbeat

### ISSUE THREAD

**Issue by dfaropennetwork** [sscarduzio/elasticsearch-readonlyrest-plugin#83]
Hi again,

I've problems with topbeat and readonly plugin i think, i suppose for the permission.

I used topbeat with the logstash output but i also try with elasticsearch but the result is the same:

**The service started correctly**

sudo tailf /var/log/syslog
Jul 22 05:25:39 ubuweb55000 /usr/bin/topbeat[64791]: async.go:92: create bulk processing worker (interval=1s, bulk size=2048)
Jul 22 05:25:39 ubuweb55000 /usr/bin/topbeat[64791]: beat.go:147: Init Beat: topbeat; Version: 1.2.3
Jul 22 05:25:39 ubuweb55000 /usr/bin/topbeat[64791]: topbeat.go:88: Init topbeat
Jul 22 05:25:39 ubuweb55000 /usr/bin/topbeat[64791]: topbeat.go:89: Follow processes [".*"]
Jul 22 05:25:39 ubuweb55000 /usr/bin/topbeat[64791]: topbeat.go:90: Period 30s
Jul 22 05:25:39 ubuweb55000 /usr/bin/topbeat[64791]: topbeat.go:91: System statistics true
Jul 22 05:25:39 ubuweb55000 /usr/bin/topbeat[64791]: topbeat.go:92: Process statistics true
Jul 22 05:25:39 ubuweb55000 /usr/bin/topbeat[64791]: topbeat.go:93: File system statistics true
Jul 22 05:25:39 ubuweb55000 /usr/bin/topbeat[64791]: topbeat.go:94: Cpu usage per core false
Jul 22 05:25:39 ubuweb55000 /usr/bin/topbeat[64791]: beat.go:173: topbeat sucessfully setup. Start running

**Topbeat recolect events**

"hostname": "ubuweb55000",#012    "name": "ubuweb55000"#012  },#012  "count": 1,#012  "fs": {#012    "device_name": "systemd",#012    "total": 0,#012    "used": 0,#012    "used_p": 0,#012    "free": 0,#012    "avail": 0,#012    "files": 0,#012    "free_files": 0,#012    "mount_point": "/sys/fs/cgroup/systemd"#012  },#012  "type": "filesystem"#012}
Jul 22 05:26:10 ubuweb55000 /usr/bin/topbeat[64791]: publish.go:109: Publish: {#012  "@timestamp": "2016-07-22T05:26:10.202Z",#012  "beat": {#012    "hostname": "ubuweb55000",#012    "name": "ubuweb55000"#012  },#012  "count": 1,#012  "fs": {#012    "device_name": "ubuint55000:/var/home",#012    "total": 16475252326400,#012    "used": 159482118144,#012    "used_p": 0.01,#012    "free": 16315770208256,#012    "avail": 15437003751424,#012    "files": 4290772992,#012    "free_files": 4290585042,#012    "mount_point": "/var/home"#012  },#012  "type": "filesystem"#012}
Jul 22 05:26:10 ubuweb55000 /usr/bin/topbeat[64791]: publish.go:109: Publish: {#012  "@timestamp": "2016-07-22T05:26:10.205Z",#012  "beat": {#012    "hostname": "ubuweb55000",#012    "name": "ubuweb55000"#012  },#012  "count": 1,#012  "fs": {#012    "device_name": "ubuglst001:/glstvol01",#012    "total": 35145721577472,#012    "used": 6906525646848,#012    "used_p": 0.2,#012    "free": 28239195930624,#012    "avail": 28239195930624,#012    "files": 6865233408,#012    "free_files": 6844473517,#012    "mount_point": "/glst"#012  },#012  "type": "filesystem"#012}

**But the event send fail:**

Jul 22 05:26:10 ubuweb55000 /usr/bin/topbeat[64791]: output.go:87: output worker: publish 376 events
Jul 22 05:26:10 ubuweb55000 /usr/bin/topbeat[64791]: client.go:100: connect

Jul 22 05:26:24 ubuweb55000 /usr/bin/topbeat[64791]: single.go:126: Connecting error publishing events (retrying): read tcp 10.55.0.4:34707->10.100.0.4:5044: read: connection reset by peer
Jul 22 05:26:24 ubuweb55000 /usr/bin/topbeat[64791]: single.go:152: send fail
Jul 22 05:26:24 ubuweb55000 /usr/bin/topbeat[64791]: single.go:159: backoff retry: 1s
Jul 22 05:26:25 ubuweb55000 /usr/bin/topbeat[64791]: client.go:100: connect

Any idea???

i try to put user and password on topbeat configuration but maybe the protocol it is incorrect (https)

  logstash:
    # The Logstash hosts
    hosts: ["machine:5044"]

    # Optional protocol and basic auth credentials.
    protocol: "https"
    username: "logstash"
    password: "logstash"

    tls:
      # List of root certificates for HTTPS server verifications
      certificate_authorities: ["/etc/okn/lalalal/lalalala.crt"]

**Comment by sscarduzio** [comment]
yeah it looks like the problem lies at the TCP/TLS layer, or anyway before the plugin has the opportunity to reject anything.

**Comment by dfaropennetwork** [comment]
For example now i configure the output to elasticserch and the error is the following;

[2016-07-23 01:33:54,701][INFO ][plugin.readonlyrest.acl  ] no block has matched, forbidding by default: { action: indices:data/write/bulk, OA:10.52.0.11, indices:[topbeat-2016.07.23], M:POST, P:/_bulk, C:<not available>, Headers:[]}
[2016-07-23 01:33:54,781][INFO ][plugin.readonlyrest.acl  ] no block has matched, forbidding by default: { action: indices:data/write/bulk, OA:10.105.1.4, indices:[topbeat-2016.07.23], M:POST, P:/_bulk, C:<not available>, Headers:[]}
[2016-07-23 01:33:54,841][INFO ][plugin.readonlyrest.acl  ] no block has matched, forbidding by default: { action: indices:data/write/bulk, OA:10.105.1.4, indices:[topbeat-2016.07.23], M:POST, P:/_bulk, C:<not available>, Headers:[]}
[2016-07-23 01:33:55,178][INFO ][plugin.readonlyrest.acl  ] no block has matched, forbidding by default: { action: indices:data/write/bulk, OA:10.52.0.6, indices:[topbeat-2016.07.23], M:POST, P:/_bulk, C:<not available>, Headers:[]}
[2016-07-23 01:33:55,186][INFO ][plugin.readonlyrest.acl  ] no block has matched, forbidding by default: { action: indices:data/write/bulk, OA:10.52.0.6, indices:[topbeat-2016.07.23], M:POST, P:/_bulk, C:{"index":{"_index":"topbeat-2016.07.23","_type":"filesystem"}}

Looks like a autentication problem, ok i put the user and password on topbeat for readonly plugin

Now the events appears on kibana, elasticsearch cath them but i see many errors on the elasticsearch log:

[2016-07-23 01:51:25,074][WARN ][http.netty               ] [machinename] Caught exception while handling client http traffic, closing connection [id: 0x7f367733, /10.104.0.5:35565 :> /10.100.0.4:9200]
java.lang.IllegalArgumentException: empty text
        at org.jboss.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:89)
        at org.jboss.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:62)
        at org.jboss.netty.handler.codec.http.HttpRequestDecoder.createMessage(HttpRequestDecoder.java:75)
        at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:191)
        at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:102)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500)


This is a problem between the topbeat protocol negociation to readonly plugin, the index info appears on kibana but i've so many errors.

**Comment by dfaropennetwork** [comment]
Http protocol work with errors and https is blocked by readonly plugin:

[2016-07-23 02:01:04,574][INFO ][plugin.readonlyrest.acl  ] no block has matched, forbidding by default: { action: indices:data/write/bulk, OA:10.102.0.4, indices:[topbeat-2016.07.23], M:POST, P:/_bulk, C:<not available>, Headers:[]}
[2016-07-23 02:01:05,593][INFO ][plugin.readonlyrest.acl  ] no block has matched, forbidding by default: { action: indices:data/write/bulk, OA:10.102.0.4, indices:[topbeat-2016.07.23], M:POST, P:/_bulk, C:<not available>, Headers:[]}
[2016-07-23 02:01:07,877][INFO ][plugin.readonlyrest.acl  ] no block has matched, forbidding by default: { action: indices:data/write/bulk, OA:10.102.0.4, indices:[topbeat-2016.07.23], M:POST, P:/_bulk, C:<not available>, Headers:[]}

**Comment by sscarduzio** [comment]
I'm travelling right now but as far as I can see you can simply add a rule to match the blocked request (last log line above this comment) and it's going to be fine!

**Comment by sscarduzio** [comment]
Right now I'm not sure what the exception is though..

**Comment by sscarduzio** [comment]
Can you show me the whole ES configuration file?

**Comment by dfaropennetwork** [comment]
Yes sure and thank you

 readonlyrest:
    enable: true
    response_if_req_forbidden: Forbidden by ReadonlyREST ES plugin
    access_control_rules:

    - name: "Logstash can write and create its own indices"
      auth_key: secret :D
      type: allow
      actions: ["indices:data/read/*","indices:data/write/*","indices:admin/template/*","indices:admin/create","indices:data/write/bulk"]
      indices: ["logstash-*", "filebeat-*","packetbeat-*", "topbeat-*"]

    - name: Kibana Server (we trust this server side component, full access granted via HTTP authentication)
      auth_key: secret
      type: allow

    - name: Developer (reads only logstash indices, but can create new charts/dashboards)
      auth_key: secret
      type: allow

      kibana_access: ro+
      indices: [".kibana*", "logstash*", "default", "filebeat*", "packetbeat*", "topbeat*"]

**Comment by ld57** [comment]
Hi,

I will test topbeat with readonly plugin next week, I will be able to tell how it goes.

**Comment by sscarduzio** [comment]
Ok mate, no rush!

**Comment by dfaropennetwork** [comment]
I forgot, the plugin works perfectly, thanks

**Comment by dfaropennetwork** [comment]
Please close the issue
